server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #路由ID可以随便写  id前,减号为多个的意思。
        - id: user-service-route
          #代理的服务器地址
          # lb标识从Eureka中获取具体服务,而不是写死
          uri: lb://user-service
            #路由断言: 可以匹配映射路径（也就是条件）
          predicates:
            - Path=/user/**
          filters:
            # 添加请求路径的前缀
#             - PrefixPath=/user
            #1 表示过滤1个路径,2表示过滤两个路径,以此类推
#            - StripPrefix=1
            - MyParam=name
#      default-filters:
#        - AddResponseHeader=X-Response-Foo,Bar
#        - AddResponseHeade=wang,ws
eureka:
  client:
    service-url:
      # eureka 服务地址，如果是集群的话；需要指定其它集群eureka地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    # 修改后在调用服务的时候,已经改成了IP地址;但需要注意,不是在Eureka中的控制台服务实例状态显示;可通过Debug查看
    ip-address: 127.0.0.1 #ip地址
    prefer-ip-address: true #更倾向于使用ip,而不是host名